import './globals.css'
import type { Metadata } from 'next'
import { Coiny} from 'next/font/google'

const font = Coiny({ subsets: ['latin'], weight:["400"] })

export const metadata: Metadata = {
  title: 'TA-TE-TI',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      
      <body className={font.className}>
        
        {children}</body>
    </html>
  )
}
